"""End-to-end audit of all QR codes generated by the BBr software.

Iterates over every ticket-producing flow, extracts the embedded QR from the
generated PNG (via pyzbar = pure-Python equivalent of a phone camera decoder),
then validates that the staff scan endpoint accepts the decoded payload.

Run via:
    pytest -xvs backend/tests/test_qr_audit_boarding.py
"""
import base64
import io
import json
import os
import re
import uuid
from datetime import datetime, timedelta, timezone

import pytest
import requests
from PIL import Image
from pyzbar.pyzbar import decode as zbar_decode

BASE_URL = os.environ.get(
    "REACT_APP_BACKEND_URL",
    "https://reserve-bbr.preview.emergentagent.com",
).rstrip("/")
API = f"{BASE_URL}/api"
ADMIN = {"email": "admin@boulay.ci", "password": "Admin@2026"}

# --- Helpers ---
@pytest.fixture(scope="session")
def admin_hdr():
    r = requests.post(f"{API}/auth/staff/login", json=ADMIN, timeout=20)
    assert r.status_code == 200, r.text
    return {"Authorization": f"Bearer {r.json()['access_token']}"}


def _decode_qr_from_data_url(data_url: str) -> str:
    """Pyzbar-decode the QR embedded inside a base64 data:image/png PNG.

    Returns the decoded text. Raises if no QR is found.
    """
    assert data_url.startswith("data:image"), f"Not a data URL: {data_url[:40]}"
    b64 = data_url.split(",", 1)[1]
    raw = base64.b64decode(b64)
    img = Image.open(io.BytesIO(raw))
    results = zbar_decode(img)
    assert results, "No QR code found in image (camera would fail to scan)"
    return results[0].data.decode("utf-8")


def _next_weekday(target_weekday: int) -> str:
    d = datetime.now(timezone.utc).date() + timedelta(days=7)
    while d.weekday() != target_weekday:
        d += timedelta(days=1)
    return d.isoformat()


def _booker(prefix="QR_AUDIT"):
    return {
        "kind": "adult",
        "name": f"{prefix}_{uuid.uuid4().hex[:5]}",
        "surname": "Audit",
        "nationality": "Ivoirienne",
        "email": f"qr_audit_{uuid.uuid4().hex[:6]}@example.com",
        "phone": "+2250700000099",
        "date_of_birth": "1990-01-01",
    }


def _create_booking(offer_type, date, boat_time, adults=2, payment_method="card"):
    participants = [_booker()]
    for i in range(adults - 1):
        participants.append({
            "kind": "adult",
            "name": f"QR_AUDIT_A{i}_{uuid.uuid4().hex[:3]}",
            "surname": "T",
            "nationality": "Française",
        })
    payload = {
        "offer_type": offer_type,
        "date": date,
        "boat_time": boat_time,
        "adults": adults,
        "children": 0,
        "participants": participants,
        "name": participants[0]["name"],
        "surname": participants[0]["surname"],
        "email": participants[0]["email"],
        "phone": participants[0]["phone"],
        "nationality": participants[0]["nationality"],
        "lang": "fr",
    }
    r = requests.post(f"{API}/bookings", json=payload, timeout=30)
    assert r.status_code == 200, r.text
    booking = r.json()
    ref = booking.get("reference_token")
    # Pay
    r2 = requests.post(
        f"{API}/bookings/{booking['id']}/pay",
        json={"payment_method": payment_method, "reference_token": ref},
        timeout=60,
    )
    assert r2.status_code == 200, r2.text
    return r2.json()


# -------- Tests --------
@pytest.mark.parametrize("offer_type,date_fn,boat_time", [
    ("pass_day", lambda: _next_weekday(2), "10H"),   # Wednesday
    ("sunset",   lambda: _next_weekday(5), "16H"),   # Saturday
    ("brunch",   lambda: _next_weekday(6), "10H"),   # Sunday
    ("le_kaai",  lambda: _next_weekday(2), "18H"),
])
def test_boarding_pass_qr_scannable(admin_hdr, offer_type, date_fn, boat_time):
    """Each paid booking generates a ticket PNG whose embedded QR decodes to
    {"type":"ticket","token":"<32hex>","ref":"<8up>"} AND is accepted by the
    staff scan endpoint without manual normalisation.
    """
    booking = _create_booking(offer_type, date_fn(), boat_time, adults=2)
    qrs = booking.get("qr_codes") or []
    assert qrs, f"No qr_codes returned for {offer_type}"

    for q in qrs:
        ticket = q.get("ticket_image")
        assert ticket, f"Missing ticket_image for {offer_type}/{q.get('label_fr')}"
        # Decode QR with pyzbar (= what the camera would do)
        decoded = _decode_qr_from_data_url(ticket)
        # Must parse as compact JSON ticket payload
        payload = json.loads(decoded)
        assert payload["type"] == "ticket"
        assert re.fullmatch(r"[0-9a-f]{32}", payload["token"])
        assert re.fullmatch(r"[0-9A-F]{8}", payload["ref"])
        # The scan endpoint must accept the raw decoded payload
        r = requests.get(f"{API}/staff/scan/{requests.utils.quote(decoded, safe='')}",
                         headers=admin_hdr, timeout=20)
        assert r.status_code == 200, f"{offer_type}: {r.text[:200]}"


def test_scanner_accepts_short_ref_code(admin_hdr):
    """The 10-char ref printed under the QR on the ticket should also resolve."""
    booking = _create_booking("pass_day", _next_weekday(2), "10H", adults=1)
    token = booking["qr_codes"][0]["qr_token"]
    short_ref = token[:10].upper()
    r = requests.get(f"{API}/staff/scan/{short_ref}",
                     headers=admin_hdr, timeout=20)
    assert r.status_code == 200, r.text
    assert r.json()["qr_token"].lower() == token.lower()


def test_scanner_accepts_booking_id_ref(admin_hdr):
    """The 8-char booking-id prefix should also resolve (iter-41 fallback)."""
    booking = _create_booking("pass_day", _next_weekday(2), "10H", adults=1)
    booking_ref = booking["id"][:8].upper()
    r = requests.get(f"{API}/staff/scan/{booking_ref}",
                     headers=admin_hdr, timeout=20)
    assert r.status_code == 200, r.text


def test_scanner_accepts_uppercase_token(admin_hdr):
    """The full 32-hex token in uppercase should be lower-cased and resolved."""
    booking = _create_booking("pass_day", _next_weekday(2), "10H", adults=1)
    token = booking["qr_codes"][0]["qr_token"]
    r = requests.get(f"{API}/staff/scan/{token.upper()}",
                     headers=admin_hdr, timeout=20)
    assert r.status_code == 200


def test_scanner_accepts_raw_json_payload(admin_hdr):
    """Some 3rd-party scanners forward the raw JSON. Resolver must extract it."""
    booking = _create_booking("pass_day", _next_weekday(2), "10H", adults=1)
    token = booking["qr_codes"][0]["qr_token"]
    booking_ref = booking["id"][:8].upper()
    raw_json = json.dumps({"type": "ticket", "token": token, "ref": booking_ref})
    r = requests.get(f"{API}/staff/scan/{requests.utils.quote(raw_json, safe='')}",
                     headers=admin_hdr, timeout=20)
    assert r.status_code == 200, r.text


def test_qr_size_above_camera_threshold(admin_hdr):
    """The embedded QR inside the ticket PNG must be at least 380px wide so a
    phone camera can decode it from a printed ticket without focus issues.
    """
    booking = _create_booking("pass_day", _next_weekday(2), "10H", adults=1)
    ticket = booking["qr_codes"][0]["ticket_image"]
    b64 = ticket.split(",", 1)[1]
    img = Image.open(io.BytesIO(base64.b64decode(b64)))
    results = zbar_decode(img)
    assert results
    rect = results[0].rect
    assert rect.width >= 380, f"QR too small ({rect.width}px) — camera scan may fail"
    assert rect.height >= 380, f"QR too small ({rect.height}px)"


def test_registration_qr_scannable(admin_hdr):
    """Self-registration QR (used by /accueil/enregistrement flow) must be
    accepted by the staff scanner.
    """
    # 1. Create a registration via the public endpoint
    payload = {
        "kind": "client",
        "first_name": "QR",
        "last_name": f"Reg_{uuid.uuid4().hex[:4]}",
        "phone": "+2250707070707",
        "email": f"qr_reg_{uuid.uuid4().hex[:5]}@example.com",
        "nationality": "Ivoirienne",
        "offer_id": "pass_day",
    }
    r = requests.post(f"{API}/registrations", json=payload, timeout=20)
    assert r.status_code == 200, r.text
    reg = r.json()
    token = reg.get("pass_token")
    assert token, f"Missing pass_token: {reg}"
    # 2. The staff scan/registration endpoint accepts the raw token
    r2 = requests.get(f"{API}/staff/scan/registration/{token}",
                      headers=admin_hdr, timeout=20)
    assert r2.status_code == 200, r2.text
    # 3. The generic /staff/scan returns 404 for registration tokens — the
    #    frontend then falls back to /staff/scan/registration (already tested).
    r3 = requests.get(f"{API}/staff/scan/{token}",
                      headers=admin_hdr, timeout=20)
    assert r3.status_code == 404
